FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS builder
WORKDIR /app
COPY CryptoBenchmark.csproj .
RUN dotnet restore
COPY Program.cs .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:9.0-alpine
WORKDIR /app
COPY --from=builder /app/out .
ENTRYPOINT ["./CryptoBenchmark"]